# Generated by Django 5.2.8 on 2025-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='moodtag_name', help_text='Человеко-читаемое название тега настроения', max_length=50, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='moodtag_created', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='moodtag_updated', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тег настроения',
                'verbose_name_plural': 'Теги настроения',
                'db_table': 'moods_moodtag',
                'ordering': ['name'],
            },
        ),
    ]
