# Generated by Django 5.2.8 on 2025-12-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('none', 'Не указывать')], default='none', max_length=10)),
                ('profile_visibility', models.CharField(choices=[('public', 'Все'), ('private', 'Никто')], default='public', max_length=20, verbose_name='Кто видит профиль')),
                ('show_events', models.BooleanField(default=True, verbose_name='Показывать участие в мероприятиях')),
                ('show_reviews', models.BooleanField(default=True, verbose_name='Показывать отзывы')),
                ('reviews_visibility', models.CharField(choices=[('public', 'Все'), ('private', 'Никто')], default='public', max_length=20, verbose_name='Видимость отзывов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
