# Generated by Django 5.2.8 on 2025-12-20 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название мероприятия')),
                ('event_text', models.TextField(blank=True, verbose_name='Описание мероприятия')),
                ('event_time_begin', models.DateTimeField(verbose_name='Дата и время начала')),
                ('event_time_end', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('event_available', models.BooleanField(default=True, verbose_name='Доступно для бронирования')),
                ('event_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на карту/сайт')),
                ('event_max_participants', models.CharField(max_length=10, verbose_name='Максимальное количество участников')),
                ('event_status', models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='active', max_length=20, verbose_name='Статус мероприятия')),
                ('event_remaining_seats', models.IntegerField(default=0, verbose_name='Оставшиеся места')),
                ('event_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель мероприятия')),
                ('mood_tags', models.ManyToManyField(blank=True, help_text='Выберите один или несколько тегов настроения', related_name='events', to='moods.moodtag', verbose_name='Теги настроения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
                'ordering': ['-event_time_begin', 'event_name'],
                'managed': True,
            },
        ),
    ]
